
export enum GAME_LOOP_STATES {
    INITIALIZE = "INITIALIZE",
    START = "START",
    PLAY = "PLAY",
    END = "END"
}

export enum STATE_ACTIONS {
    SETUP = "SETUP",
    PROCESS = "PROCESS",
    END_PROCESS = "END_PROCESS",
    COMPLETE = "COMPLETE"
}